-- AlterTable
ALTER TABLE "Ticket" ADD COLUMN     "fromLat" DOUBLE PRECISION,
ADD COLUMN     "fromLon" DOUBLE PRECISION,
ADD COLUMN     "toLat" DOUBLE PRECISION,
ADD COLUMN     "toLon" DOUBLE PRECISION;
